// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: api/proto/src/models.proto

package voucherApi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoucherType int32

const (
	Voucher_Voucher VoucherType = 0
	Voucher_Credit  VoucherType = 1
)

// Enum value maps for VoucherType.
var (
	VoucherType_name = map[int32]string{
		0: "Voucher",
		1: "Credit",
	}
	VoucherType_value = map[string]int32{
		"Voucher": 0,
		"Credit":  1,
	}
)

func (x VoucherType) Enum() *VoucherType {
	p := new(VoucherType)
	*p = x
	return p
}

func (x VoucherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoucherType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_src_models_proto_enumTypes[0].Descriptor()
}

func (VoucherType) Type() protoreflect.EnumType {
	return &file_api_proto_src_models_proto_enumTypes[0]
}

func (x VoucherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoucherType.Descriptor instead.
func (VoucherType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_src_models_proto_rawDescGZIP(), []int{1, 0}
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_api_proto_src_models_proto_rawDescGZIP(), []int{0}
}

type Voucher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"created_at"
	CreatedAt int64 `protobuf:"varint,2,opt,name=CreatedAt,proto3" json:"created_at"`
	// @inject_tag: json:"updated_at"
	UpdatedAt int64 `protobuf:"varint,3,opt,name=UpdatedAt,proto3" json:"updated_at"`
	// @inject_tag: json:"max_amount"
	MaxAmount int64 `protobuf:"varint,4,opt,name=MaxAmount,proto3" json:"max_amount"`
	// @inject_tag: json:"usage_limit"
	UsageLimit int64 `protobuf:"varint,5,opt,name=UsageLimit,proto3" json:"usage_limit"`
	// @inject_tag: json:"discount"
	Discount int32 `protobuf:"varint,6,opt,name=Discount,proto3" json:"discount"`
	// @inject_tag: json:"code"
	Code string `protobuf:"bytes,7,opt,name=Code,proto3" json:"code"`
	// @inject_tag: json:"start_time"
	StartTime int64 `protobuf:"varint,8,opt,name=StartTime,proto3" json:"start_time"`
	// @inject_tag: json:"expiration_time"
	ExpirationTime int64 `protobuf:"varint,9,opt,name=ExpirationTime,proto3" json:"expiration_time"`
	// @inject_tag: json:"description"
	Description string `protobuf:"bytes,10,opt,name=Description,proto3" json:"description"`
	// @inject_tag: json:"amount"
	Amount int64 `protobuf:"varint,11,opt,name=Amount,proto3" json:"amount"`
	// @inject_tag: json:"type"
	Type VoucherType `protobuf:"varint,12,opt,name=Type,proto3,enum=voucher_api.VoucherType" json:"type"`
}

func (x *Voucher) Reset() {
	*x = Voucher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voucher) ProtoMessage() {}

func (x *Voucher) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voucher.ProtoReflect.Descriptor instead.
func (*Voucher) Descriptor() ([]byte, []int) {
	return file_api_proto_src_models_proto_rawDescGZIP(), []int{1}
}

func (x *Voucher) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Voucher) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Voucher) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Voucher) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *Voucher) GetUsageLimit() int64 {
	if x != nil {
		return x.UsageLimit
	}
	return 0
}

func (x *Voucher) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Voucher) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Voucher) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Voucher) GetExpirationTime() int64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

func (x *Voucher) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Voucher) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Voucher) GetType() VoucherType {
	if x != nil {
		return x.Type
	}
	return Voucher_Voucher
}

type Usages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"voucher"
	Voucher *Voucher `protobuf:"bytes,1,opt,name=Voucher,proto3" json:"voucher"`
	// @inject_tag: json:"phone_numbers"
	PhoneNumbers []string `protobuf:"bytes,2,rep,name=PhoneNumbers,proto3" json:"phone_numbers"`
}

func (x *Usages) Reset() {
	*x = Usages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usages) ProtoMessage() {}

func (x *Usages) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usages.ProtoReflect.Descriptor instead.
func (*Usages) Descriptor() ([]byte, []int) {
	return file_api_proto_src_models_proto_rawDescGZIP(), []int{2}
}

func (x *Usages) GetVoucher() *Voucher {
	if x != nil {
		return x.Voucher
	}
	return nil
}

func (x *Usages) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

var File_api_proto_src_models_proto protoreflect.FileDescriptor

var file_api_proto_src_models_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x76, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69,
	0x64, 0x22, 0x93, 0x03, 0x0a, 0x07, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x78,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4d, 0x61,
	0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x10, 0x01, 0x22, 0x5c, 0x0a, 0x06, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x2e, 0x0a, 0x07, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x07, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x2d, 0x76, 0x61, 0x72, 0x6d, 0x61, 0x7a, 0x79, 0x61, 0x72, 0x2f,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_src_models_proto_rawDescOnce sync.Once
	file_api_proto_src_models_proto_rawDescData = file_api_proto_src_models_proto_rawDesc
)

func file_api_proto_src_models_proto_rawDescGZIP() []byte {
	file_api_proto_src_models_proto_rawDescOnce.Do(func() {
		file_api_proto_src_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_src_models_proto_rawDescData)
	})
	return file_api_proto_src_models_proto_rawDescData
}

var file_api_proto_src_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_src_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_src_models_proto_goTypes = []interface{}{
	(VoucherType)(0), // 0: voucher_api.Voucher.type
	(*Void)(nil),     // 1: voucher_api.Void
	(*Voucher)(nil),  // 2: voucher_api.Voucher
	(*Usages)(nil),   // 3: voucher_api.Usages
}
var file_api_proto_src_models_proto_depIdxs = []int32{
	0, // 0: voucher_api.Voucher.Type:type_name -> voucher_api.Voucher.type
	2, // 1: voucher_api.Usages.Voucher:type_name -> voucher_api.Voucher
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_src_models_proto_init() }
func file_api_proto_src_models_proto_init() {
	if File_api_proto_src_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_src_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voucher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_src_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_src_models_proto_goTypes,
		DependencyIndexes: file_api_proto_src_models_proto_depIdxs,
		EnumInfos:         file_api_proto_src_models_proto_enumTypes,
		MessageInfos:      file_api_proto_src_models_proto_msgTypes,
	}.Build()
	File_api_proto_src_models_proto = out.File
	file_api_proto_src_models_proto_rawDesc = nil
	file_api_proto_src_models_proto_goTypes = nil
	file_api_proto_src_models_proto_depIdxs = nil
}
