// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: api/proto/src/voucher.proto

package voucherApi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoucherCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"max_amount,omitempty"
	MaxAmount int64 `protobuf:"varint,1,opt,name=MaxAmount,proto3" json:"max_amount,omitempty"`
	// @inject_tag: json:"usage_limit,omitempty"
	UsageLimit int64 `protobuf:"varint,2,opt,name=UsageLimit,proto3" json:"usage_limit,omitempty"`
	// @inject_tag: json:"discount,omitempty"
	Discount int32 `protobuf:"varint,3,opt,name=Discount,proto3" json:"discount,omitempty"`
	// @inject_tag: json:"code"
	Code string `protobuf:"bytes,4,opt,name=Code,proto3" json:"code"`
	// @inject_tag: json:"start_time,omitempty"
	StartTime int64 `protobuf:"varint,5,opt,name=StartTime,proto3" json:"start_time,omitempty"`
	// @inject_tag: json:"expiration_time,omitempty"
	ExpirationTime int64 `protobuf:"varint,6,opt,name=ExpirationTime,proto3" json:"expiration_time,omitempty"`
	// @inject_tag: json:"description,omitempty"
	Description string `protobuf:"bytes,7,opt,name=Description,proto3" json:"description,omitempty"`
	// @inject_tag: json:"amount,omitempty"
	Amount int64 `protobuf:"varint,8,opt,name=Amount,proto3" json:"amount,omitempty"`
	// @inject_tag: json:"type"
	Type VoucherType `protobuf:"varint,9,opt,name=Type,proto3,enum=voucher_api.VoucherType" json:"type"`
}

func (x *VoucherCreateReq) Reset() {
	*x = VoucherCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_voucher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherCreateReq) ProtoMessage() {}

func (x *VoucherCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_voucher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherCreateReq.ProtoReflect.Descriptor instead.
func (*VoucherCreateReq) Descriptor() ([]byte, []int) {
	return file_api_proto_src_voucher_proto_rawDescGZIP(), []int{0}
}

func (x *VoucherCreateReq) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *VoucherCreateReq) GetUsageLimit() int64 {
	if x != nil {
		return x.UsageLimit
	}
	return 0
}

func (x *VoucherCreateReq) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *VoucherCreateReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VoucherCreateReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VoucherCreateReq) GetExpirationTime() int64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

func (x *VoucherCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VoucherCreateReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *VoucherCreateReq) GetType() VoucherType {
	if x != nil {
		return x.Type
	}
	return Voucher_Voucher
}

type VoucherApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"code"
	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"code"`
	// @inject_tag: json:"phone_number"
	PhoneNumber string `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"phone_number"`
}

func (x *VoucherApplyReq) Reset() {
	*x = VoucherApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_voucher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherApplyReq) ProtoMessage() {}

func (x *VoucherApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_voucher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherApplyReq.ProtoReflect.Descriptor instead.
func (*VoucherApplyReq) Descriptor() ([]byte, []int) {
	return file_api_proto_src_voucher_proto_rawDescGZIP(), []int{1}
}

func (x *VoucherApplyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VoucherApplyReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type VoucherUsageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"identifier"
	//
	// Types that are assignable to Identifier:
	//	*VoucherUsageReq_Code
	//	*VoucherUsageReq_ID
	Identifier isVoucherUsageReq_Identifier `protobuf_oneof:"Identifier" json:"identifier"`
}

func (x *VoucherUsageReq) Reset() {
	*x = VoucherUsageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_voucher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherUsageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherUsageReq) ProtoMessage() {}

func (x *VoucherUsageReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_voucher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherUsageReq.ProtoReflect.Descriptor instead.
func (*VoucherUsageReq) Descriptor() ([]byte, []int) {
	return file_api_proto_src_voucher_proto_rawDescGZIP(), []int{2}
}

func (m *VoucherUsageReq) GetIdentifier() isVoucherUsageReq_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (x *VoucherUsageReq) GetCode() string {
	if x, ok := x.GetIdentifier().(*VoucherUsageReq_Code); ok {
		return x.Code
	}
	return ""
}

func (x *VoucherUsageReq) GetID() string {
	if x, ok := x.GetIdentifier().(*VoucherUsageReq_ID); ok {
		return x.ID
	}
	return ""
}

type isVoucherUsageReq_Identifier interface {
	isVoucherUsageReq_Identifier()
}

type VoucherUsageReq_Code struct {
	// @inject_tag: json:"code"
	Code string `protobuf:"bytes,1,opt,name=Code,proto3,oneof" json:"code"`
}

type VoucherUsageReq_ID struct {
	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,2,opt,name=ID,proto3,oneof" json:"id"`
}

func (*VoucherUsageReq_Code) isVoucherUsageReq_Identifier() {}

func (*VoucherUsageReq_ID) isVoucherUsageReq_Identifier() {}

var File_api_proto_src_voucher_proto protoreflect.FileDescriptor

var file_api_proto_src_voucher_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x76,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1a, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x02, 0x0a, 0x10, 0x56, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x4d,
	0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x4d, 0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x56, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x47, 0x0a, 0x0f, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x49, 0x44, 0x42, 0x0c, 0x0a, 0x0a,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x32, 0xc5, 0x01, 0x0a, 0x0e, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x05,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1c, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x2d, 0x76, 0x61, 0x72, 0x6d, 0x61, 0x7a, 0x79, 0x61, 0x72, 0x2f, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x76,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_proto_src_voucher_proto_rawDescOnce sync.Once
	file_api_proto_src_voucher_proto_rawDescData = file_api_proto_src_voucher_proto_rawDesc
)

func file_api_proto_src_voucher_proto_rawDescGZIP() []byte {
	file_api_proto_src_voucher_proto_rawDescOnce.Do(func() {
		file_api_proto_src_voucher_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_src_voucher_proto_rawDescData)
	})
	return file_api_proto_src_voucher_proto_rawDescData
}

var file_api_proto_src_voucher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_src_voucher_proto_goTypes = []interface{}{
	(*VoucherCreateReq)(nil), // 0: voucher_api.VoucherCreateReq
	(*VoucherApplyReq)(nil),  // 1: voucher_api.VoucherApplyReq
	(*VoucherUsageReq)(nil),  // 2: voucher_api.VoucherUsageReq
	(VoucherType)(0),         // 3: voucher_api.Voucher.type
	(*Voucher)(nil),          // 4: voucher_api.Voucher
	(*Void)(nil),             // 5: voucher_api.Void
	(*Usages)(nil),           // 6: voucher_api.Usages
}
var file_api_proto_src_voucher_proto_depIdxs = []int32{
	3, // 0: voucher_api.VoucherCreateReq.Type:type_name -> voucher_api.Voucher.type
	0, // 1: voucher_api.VoucherService.Create:input_type -> voucher_api.VoucherCreateReq
	1, // 2: voucher_api.VoucherService.Apply:input_type -> voucher_api.VoucherApplyReq
	2, // 3: voucher_api.VoucherService.Usage:input_type -> voucher_api.VoucherUsageReq
	4, // 4: voucher_api.VoucherService.Create:output_type -> voucher_api.Voucher
	5, // 5: voucher_api.VoucherService.Apply:output_type -> voucher_api.Void
	6, // 6: voucher_api.VoucherService.Usage:output_type -> voucher_api.Usages
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_src_voucher_proto_init() }
func file_api_proto_src_voucher_proto_init() {
	if File_api_proto_src_voucher_proto != nil {
		return
	}
	file_api_proto_src_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_src_voucher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_voucher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_voucher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherUsageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_src_voucher_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*VoucherUsageReq_Code)(nil),
		(*VoucherUsageReq_ID)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_src_voucher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_src_voucher_proto_goTypes,
		DependencyIndexes: file_api_proto_src_voucher_proto_depIdxs,
		MessageInfos:      file_api_proto_src_voucher_proto_msgTypes,
	}.Build()
	File_api_proto_src_voucher_proto = out.File
	file_api_proto_src_voucher_proto_rawDesc = nil
	file_api_proto_src_voucher_proto_goTypes = nil
	file_api_proto_src_voucher_proto_depIdxs = nil
}
